site_name: 'VAE project'
# repo_url: https://github.com/andr-groth/cdo-scripts
nav:
  - Overview: index.md
  - Build model:
    - Models: VAE.models.md
    - Layers: VAE.layers.md
  - Train model:
    - Losses: VAE.losses.md
    - Callbacks: VAE.callbacks.md
    - Logs: VAE.logs.md
    - Generators: VAE.generators.md
    - Beta Scheduler: VAE.utils.beta_schedulers.md
  - Utils:
    - FileIO: VAE.utils.fileio.md
    - Mathematical functions: VAE.utils.math.md
    - Helper functions: VAE.utils.collection.md
    - Plot functions: VAE.utils.plot.md
  - Examples:
    - VAE: example_VAE.md
    - VAEp: example_VAEp.md
markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_section_style: list
            members_order: source
            merge_init_into_class: true
            docstring_options:
              ignore_init_summary: true
            show_object_full_path: true
            separate_signature: true
            show_root_heading: true
            show_object_full_path: true
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/andr-groth
copyright: Copyright &copy; 2023 Andreas Groth
theme:
  name: material
  features:
    - navigation.top
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - search.suggest
    - search.highlight
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
watch:
  - VAE